# Demo Configuration for Quick Training (5-10 minutes)

# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  image_width: 224
  image_height: 224
  batch_size: 16
  num_workers: 2

# Model Configuration
model:
  name: "resnet18"  # Smaller, faster model for demo
  pretrained: true
  num_outputs: 1
  freeze_backbone: false
  freeze_layers: 0

# Training Configuration
training:
  num_epochs: 10  # Short training for demo
  learning_rate: 0.001  # Higher LR for faster convergence
  optimizer: "adam"
  scheduler: "reduce_on_plateau"
  weight_decay: 0.0001
  early_stopping_patience: 5
  gradient_clip: 1.0

# Loss Configuration
loss:
  type: "mse"

# Checkpoint Configuration
checkpoint:
  save_dir: "checkpoints"
  save_frequency: 2
  save_best_only: true

# Logging Configuration
logging:
  log_dir: "logs"
  tensorboard: true
  print_frequency: 5

# Augmentation Configuration
augmentation:
  horizontal_flip: true
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1
  rotation: 5
  random_crop: false

